/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Nyilonelycompany (https://sketchfab.com/Nyilonelycompany)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/airplane-n061213-c1a7a7e1da204476879abc0909a621f2
title: Airplane N061213
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Scene(props) {
  const { nodes, materials } = useGLTF('/airplane/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, -331.55]} rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 331.55, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.Material} />
          </group>
        </group>
        <group position={[0, 0, -331.55]} rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 331.55, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_7.geometry} material={materials.Material} />
          </group>
        </group>
        <group position={[0, 0, -331.55]} rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 331.55, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_10.geometry} material={materials.Material} />
            <mesh geometry={nodes.Object_11.geometry} material={materials.Material} />
            <mesh geometry={nodes.Object_12.geometry} material={materials.Material} />
          </group>
          <group position={[0, 331.55, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_14.geometry} material={materials.Material} />
          </group>
        </group>
        <group position={[0, 0, -331.55]} rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 331.55, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_17.geometry} material={materials.Material} />
          </group>
        </group>
        <group position={[0, 0, -331.55]} rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 331.55, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_20.geometry} material={materials.Material} />
          </group>
        </group>
        <group position={[0, 0, -331.55]} rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 331.55, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_23.geometry} material={materials.Material} />
          </group>
        </group>
        <group position={[0, 0, -331.55]} rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 331.55, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_26.geometry} material={materials.Material} />
          </group>
        </group>
        <group position={[0, 0, -331.55]} rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 331.55, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_29.geometry} material={materials.Material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./minecraft/scene.gltf')
